# Generated by Django 3.2.4 on 2022-11-29 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantuan', '0002_alter_tv_play_introduction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tv_play',
            name='introduction',
            field=models.CharField(max_length=1000, verbose_name='简介'),
        ),
    ]
