# Generated by Django 3.2.4 on 2022-11-30 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fantuan', '0004_tv_video'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tv_video',
            old_name='videoid',
            new_name='video',
        ),
    ]
