# Generated by Django 3.2.4 on 2022-11-30 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fantuan', '0005_rename_videoid_tv_video_video'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tv_video',
            old_name='video',
            new_name='tv_play',
        ),
    ]
