# Generated by Django 3.2.4 on 2022-11-30 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantuan', '0006_rename_video_tv_video_tv_play'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tv_video',
            name='api_from',
            field=models.CharField(max_length=10, verbose_name='接口名'),
        ),
    ]
