# Generated by Django 3.2.4 on 2022-12-06 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantuan', '0007_alter_tv_video_api_from'),
    ]

    operations = [
        migrations.CreateModel(
            name='movie_play',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_show', models.BooleanField(default=True, verbose_name='是否显示')),
                ('orders', models.IntegerField(default=1, verbose_name='排序')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='电影名')),
                ('img_url', models.CharField(max_length=1000, verbose_name='图片地址')),
                ('note', models.CharField(max_length=100, verbose_name='更新状态')),
                ('detail_url', models.CharField(max_length=1000, verbose_name='详情页面地址')),
                ('type', models.CharField(max_length=100, verbose_name='类型')),
                ('region', models.CharField(max_length=20, verbose_name='地区')),
                ('year', models.CharField(max_length=20, verbose_name='年份')),
                ('performer', models.CharField(max_length=20, verbose_name='演员')),
                ('director', models.CharField(max_length=20, verbose_name='导演')),
                ('introduction', models.CharField(max_length=1000, verbose_name='简介')),
            ],
            options={
                'verbose_name': '电影列表',
                'verbose_name_plural': '电影列表',
                'db_table': 'movie_play',
            },
        ),
    ]
