# Generated by Django 3.2.4 on 2022-12-08 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fantuan', '0009_movie_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie_video',
            name='tv_play',
        ),
        migrations.AddField(
            model_name='movie_video',
            name='movie_play',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fantuan.movie_play', verbose_name='电影id'),
        ),
    ]
