# Generated by Django 3.2.4 on 2022-12-08 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantuan', '0010_auto_20221208_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie_video',
            name='video_url',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='m3u8地址'),
        ),
    ]
