# Generated by Django 3.2.4 on 2023-02-04 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fantuan', '0011_alter_movie_video_video_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tv_video',
            name='video_url',
        ),
    ]
