# Generated by Django 3.2.4 on 2022-10-19 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartoon_menu',
            options={'verbose_name': '动漫目录', 'verbose_name_plural': '动漫目录'},
        ),
        migrations.AlterModelTable(
            name='cartoon_menu',
            table='cartoon_menu',
        ),
    ]
