# Generated by Django 3.2.4 on 2022-10-19 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_auto_20221019_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartoon_menu',
            name='is_show',
            field=models.BooleanField(default=True, verbose_name='是否显示'),
        ),
    ]
