# Generated by Django 3.2.4 on 2022-10-19 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_alter_cartoon_menu_is_show'),
    ]

    operations = [
        migrations.CreateModel(
            name='cartoon_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_show', models.BooleanField(default=True, verbose_name='是否显示')),
                ('orders', models.IntegerField(default=1, verbose_name='排序')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('name', models.CharField(max_length=50, verbose_name='动漫名称')),
                ('years', models.CharField(max_length=10, verbose_name='发行年份')),
                ('country', models.CharField(max_length=10, verbose_name='发行国家')),
                ('tag', models.CharField(max_length=50, verbose_name='动漫标签')),
                ('introduction', models.CharField(max_length=1000, verbose_name='动漫简介')),
                ('cartoon_menu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cartoonmenu', to='menu.cartoon_menu', verbose_name='动漫目录')),
            ],
            options={
                'verbose_name': '动漫详情',
                'verbose_name_plural': '动漫详情',
                'db_table': 'cartoon_detail',
            },
        ),
        migrations.CreateModel(
            name='player_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_show', models.BooleanField(default=True, verbose_name='是否显示')),
                ('orders', models.IntegerField(default=1, verbose_name='排序')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('episode', models.CharField(max_length=10)),
                ('player_url', models.CharField(max_length=1000)),
                ('cartoon_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.cartoon_detail', verbose_name='动漫名称')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='cartoon_menu',
            name='cartoon_detail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cartoondetail', to='menu.cartoon_detail', verbose_name='动漫详情'),
        ),
    ]
