# Generated by Django 3.2.4 on 2022-10-19 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_auto_20221019_1546'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='player_list',
            options={'verbose_name': '播放列表', 'verbose_name_plural': '播放列表'},
        ),
        migrations.RemoveField(
            model_name='player_list',
            name='cartoon_detail',
        ),
        migrations.AddField(
            model_name='player_list',
            name='cartoon_menu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='menu.cartoon_menu', verbose_name='动漫'),
        ),
        migrations.AddField(
            model_name='player_list',
            name='name',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='player_list',
            name='episode',
            field=models.CharField(max_length=10, verbose_name='第几集'),
        ),
        migrations.AlterField(
            model_name='player_list',
            name='player_url',
            field=models.CharField(max_length=1000, verbose_name='播放地址'),
        ),
        migrations.AlterModelTable(
            name='player_list',
            table='player_list',
        ),
    ]
