# Generated by Django 3.2.4 on 2022-10-19 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_auto_20221019_1703'),
    ]

    operations = [
        migrations.AddField(
            model_name='player_list',
            name='m3u8_url',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='m3u8地址'),
        ),
    ]
